### ISSUE TITLE
What to do after doing a local setup using master branch ?

### ISSUE THREAD

**Issue by sandeepnegi1996** [henri-tremblay/refactoring#1]
Hi henri,

I have setup a local setup of the project using master branch can you guide for begineers who is just starting what needs to be done next ?

**Comment by henri-tremblay** [comment]
There are no rules. The goal is to make the core more readable, testable, understandable.

Some possibly helpful guidelines:
* No static methods with functional content
* Tests should be as readable as the code
* Method should be a big maximum of 10 lines (5 is better)
* Cyclomatic complexity of a method should be below 5
* Performance should be about the same or improve
* Use dependency injection
* Remove everything that changes over time in your tests (random numbers, current time)

3 books are helpful:
* Working effectively with legacy code - Michael Feathers
* Refactoring - Martin Fowler
* Domain Driven Design - Eric Evans

Please tell me how it goes.

**Comment by sandeepnegi1996** [comment]
Hi henri,

Thank you for the detailed explanation, I will start refactoring it as soon as possible
